apiVersion: v1
kind: Service
metadata:
  name: mylogin-svc
  labels:
    app: mylogin
spec:
   type: NodePort
   ports:
   - port: 8080
     nodePort: 30001
     protocol: TCP
   selector:
      app: mylogin   
